### ISSUE TITLE
Updatable Hyperdrive using the dat-sdk

### ISSUE THREAD

**Issue by dgrmunch** [RangerMauve/dat-workshop#1]
Imagine that I want to create a hyperdrive and write some files in it. I can do this.

```
const SDK = require('dat-sdk')

async function main(){

    try {

        var {
            Hyperdrive,
            close
          } = await SDK({
            persist: false
          })

        const drive = Hyperdrive('new-drive')

        await drive.ready()

        const url = `hyper://${drive.key.toString('hex')}`
        console.log(`New hyperdrive here: ${url}`)

        await drive.writeFile('/test.md', '# Title \n * Bullet 1 \n * Bullet 2 \n\n Regular text 2.')
        console.log('Written markdown file!')

        //await drive.close()
    
    } finally {
        //await close()
   }
}

main().catch((e) => {
    process.nextTick(() => {
      throw e
    })
  })
```

I have commented the lines `await close()` and `await drive.close()` to keep seeding the file while the process is running.

Then I go to beaker and paste the generated url with the key: 
hyper://e19a0dcf072e89d91192011a2a681ec944063dbffeba636b6d723ad36d3e542a

It says "Hyperdrive Not Found".

I try the same, but changing `persists: false` to `persists: true`

I go to beaker, paste the new url  hyper://99c9c58be1b036a24e0729aabe2132e65bdad16707616e871c2a77ba0d535edc
and this time I can see the `test.md` file.

Questions:

1) Why I can not access the hyperdrive if the `persists` flag is false?
2) Where is the drive persisted?
3) If I rename the Hyperdrive in the constructor and force another instance in order to create a new key, I try the same and In beaker does not load. What I am doing wrong in terms of seeding and persistence? I think I am missing something.
4) How can I update the same drive from the same computer in the future? I have tried forcing a key of a previously created hyperdrive and it does not let me write new files.

**Comment by RangerMauve** [comment]
Are you using this in node.js or on the web?

When you use Node it's using the [env-paths](https://github.com/sindresorhus/env-paths) module to store it in the data folder for whatever OS you're on. On web it uses [random-access-web](https://github.com/random-access-storage/random-access-web) to store data in whatever is the fastest method in your current browser.

If you set `persist:false`, it won't save stuff to disk and it'll keep it in memory. Every time you boot the SDK again it'll be as though it's starting from scratch and the same name will result in fresh Hyperdrives with different URLs.

If you set it to `true`, every time you call `Hyperdrive(name)` with the same name, it will result in the same URL each time.

If you want to write to the drive in the future, you'll want to keep `persist:true` so that the secret key will be saved.

I'm not sure why non-persisted wouldn't be getting replicated by beaker. Are you sure you aren't closing your process before Beaker has a chance to load your drive?

**Comment by dgrmunch** [comment]
Thanks! I made some adjustments and... tachán! **With Agregore it worked well!!** :D 
I wonder if there is a way to specify a location for the private key, so there is a way to easily migrate it from one device to other or make a backup easily.

**Comment by RangerMauve** [comment]
Yeah, doing backups and migrations can be tricky. :/ Would you mind opening an issue in dat-sdk to track that?

**Comment by dgrmunch** [comment]
Sure! I'll do it in a minute!

**Comment by dgrmunch** [comment]
Open new issue here: https://github.com/RangerMauve/dat-workshop/issues/2
